site_name: Flexitext
site_url: https://example.com/
nav:
  - Introduction: index.md
  - Usage:
      - Functional
      - OOP
repo_url: https://github.com/tomicapretto/flexitext
repo_name: tomicapretto/flexitext
theme:
  name: material
  palette:
    accent: blue
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  #logo: assets/logo.png
extra_css:
  - assets/stylesheets/colors.css
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
